apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  annotations: 
    volume.beta.kubernetes.io/storage-class: default
  name: azure-managed-disk
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi