apiVersion: v1
kind: Pod
metadata:
 name: azure-disk-pod
spec:
 containers:
  - image: vagabondan/minecraft-server
    name: azure
    volumeMounts:
      - name: azure
        mountPath: /data
 volumes:
      - name: azure
        azureDisk:
          kind: Managed
          diskName: myAKSDisk
          diskURI: /subscriptions/2d471e05-a69c-4422-85bf-f8a7c8897ed8/resourceGroups/OpenHack-6-Group/providers/Microsoft.Compute/disks/OpenHack-6-Disk