apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment
  labels:
    app: minecraft
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: openhack/minecraft-server:1.0
          ports:
            - containerPort: 25565
              name: game
            - containerPort: 25575
              name: console
          env:
            - name: EULA
              value: "TRUE"