apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "minecraft"
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: openhack/minecraft-server:1.0
        ports:
        - containerPort: 25565
          name: game
        - containerPort: 25575
          name: console
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - name: www
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi