apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    run: minecraft
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
  - port: 25575
    targetPort: 25575
    protocol: TCP
  selector:
    run: minecraft