apiVersion: v1
kind: Service
metadata:
  name: m2
  labels:
    app: m2
spec:
  type: LoadBalancer
  selector:
    app: m2
  ports:
  - name: game
    port: 25565
    targetPort: game
    protocol: TCP
  - name: console
    port: 25575
    targetPort: console
    protocol: TCP
